server:
  host: 192.168.205.56
spring:
  jwt:
    accessSecret: VjJ0U1MxWXlSbGRqU0ZKc1UwVktjMVZXVVhkUFVUMDk=
    refreshSecret: VjFaV2IyTXlVWGhqUm1oVVlteHdjMVl3VlhkUFVUMDk=
  jpa:
    database: mysql
    hibernate:
        format_sql: true
        use_sql_comments: true
        ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
    show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: s22055@gsm.hs.kr
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: pwgstxusbuavkrnm
  redis:
    host: localhost
    port: 6379
  main:
    allow-bean-definition-overriding: 'true'
  datasource:
    password: gree7942
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/workout?serverTimezone=UTC&characterEncoding=UTF-8
overriding: 'true'
