spring:
  jpa:
    generate-ddl: 'false'
    database: mysql
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
    show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: s22055@gsm.hs.kr
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: gree7942
  redis:
    host: 127.0.0.1
    port: '6379'
  main:
    allow-bean-definition-overriding: 'true'
  datasource:
    password: gree7942
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/workout?serverTimezone=UTC&characterEncoding=UTF-8
overriding: 'true'
